Improve CI setup
- Use Maven Wrapper
- Use GitHub's values for various URLs, branch names, etc.
- Use BouncyCastle for signing
- etc

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,4 +1,4 @@
-# Copyright 2024 lbruun.net.
+# Copyright 2025 lbruun.net.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -40,12 +40,42 @@ jobs:
           server-id: maven-central # Value of <id> in <server> section of generated settings.xml
           server-username: MAVEN_CENTRAL_USERNAME # env variable for username in <server> section of generated settings.xml
           server-password: MAVEN_CENTRAL_PASSWORD # env variable for password in <server> section of generated settings.xml
-          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }} # Value of the GPG private key to import
-          gpg-passphrase: MAVEN_CENTRAL_GPG_PASSPHRASE # env variable for GPG private key passphrase
+
+
+        # Check if the git tag complies with SemVer rules
+      - name: Check version string
+        if:  ${{ github.event_name == 'release' }}
+        run: |
+          semver_regex='^v?([0-9]+\.[0-9]+\.[0-9]+(\-[0-9a-zA-Z.]+)*)$'
+          if [ "$GITHUB_REF_TYPE" = "tag" ]; then
+            # Does tag look like a SemVer string?
+            if [[ "$GITHUB_REF_NAME" =~ $semver_regex ]]; then
+              echo "Verified: Git tag \"${GITHUB_REF_NAME#v}\" is a valid semantic versioning string."
+            else
+              echo "ERROR: Git tag \"${GITHUB_REF_NAME}\" is not a valid semantic versioning string."
+              echo "       Cannot create release !"
+              exit 1
+            fi
+          fi
+
 
       - name: Maven execution
-        run: .github/scripts/maven-execution.sh
+        run: |
+          ./mvnw \
+            --show-version \
+            --batch-mode \
+            --no-transfer-progress \
+            -Dci.project.url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" \
+            -Dci.scm.tag="${GITHUB_REF_NAME}" \
+            -Drevision="${GITHUB_REF_NAME#v}" \
+            -P$MVN_PROFILES \
+              $MVN_PHASE
         env:
+          MVN_PHASE: ${{ github.event_name == 'release' && 'deploy' || 'verify' }}
+          MVN_PROFILES: ${{ github.event_name == 'release' && '"publication"' || '""' }}
+          # The following 2 env vars are used by the Maven GPG Plugin
+          MAVEN_GPG_KEY: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }}
+          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
+          # The following 2 env vars are used when uploading to Central
           MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }} # Must be the token "username", not the username for the UI
           MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }} # Must be the token "password", not the password for the UI
-          MAVEN_CENTRAL_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
